In [2]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,19,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 19, 11, 12, 13, 14]])

In [6]:
#get a specific element [r,c], the elment number 5 from the first row
a[1,5]

13

In [8]:
#get the first row , starting form the 0 numeration
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
#obtian the number six, in due that we are only requiring one elemnt is not necesasary to put ":" 
a[0,5]

6

In [10]:
#obtain all the elemnts of the second row
a[1,:]

array([ 8,  9, 19, 11, 12, 13, 14])

In [11]:
#obtain all the elemnts of the first row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
#[startindex:endindex:stepsize]
a[0,1:6:2] 

array([2, 4, 6])

In [15]:
#[startindex:endindex:stepsize] 3 in 3 starting from the final 
a[0,1:6:3]

array([2, 5])

In [16]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [19]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [20]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [21]:
np.random.rand(4,2)

array([[0.02814819, 0.54774249],
       [0.9469789 , 0.45644212],
       [0.0470317 , 0.88089984],
       [0.7690475 , 0.92409887]])

In [22]:
np.random.randint(7,size=(3,3))

array([[3, 6, 1],
       [4, 2, 0],
       [0, 4, 1]])

In [23]:
np.random.randint(4,size=(4,4))

array([[1, 1, 0, 2],
       [0, 3, 2, 1],
       [2, 3, 1, 3],
       [2, 1, 3, 2]])

In [24]:
np.random.randint(3,size=(2,2))

array([[0, 0],
       [0, 2]])

In [25]:
np.random.randint(3,size=(5,5))

array([[0, 1, 2, 0, 2],
       [1, 2, 0, 0, 2],
       [1, 0, 0, 2, 0],
       [2, 1, 1, 0, 1],
       [0, 0, 1, 0, 0]])

In [26]:
np.random.randint(1,size=(1,1))

array([[0]])

In [28]:
np.random.randint(34,size=(9,9))

array([[20,  3, 32, 19, 28, 27, 25, 13, 16],
       [ 6, 22, 12, 24, 24,  2, 30, 19, 17],
       [21, 18, 29, 10, 11,  1,  0,  2,  5],
       [32, 27, 11,  2, 10,  5,  1, 30, 23],
       [21, 19, 26, 19,  6, 16, 17, 24, 18],
       [ 5,  9, 18, 15,  5, 10, 18, 22, 28],
       [31, 19, 11,  6, 23, 12,  5, 31, 11],
       [14, 29,  0,  2, 21, 29,  2,  2, 23],
       [10, 20, 30,  1, 22, 21, 22, 29,  1]])

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [38]:
#if is axis 1 are going to be agregated by row and is by column are going to be agregated in rows 
output = np.ones((3,2))
r2 = np.repeat(output,3,axis=1)
r2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
a = np.ones((2,3))
b = np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])